---
title: "Advanced numerics: advection with high spatial accuracy"
author: "Chiel van Heerwaarden"
date: "1/27/2019"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(plotly)
```

## Introduction
Hydrological and meteorological forecasting is often done under time pressure. Therefore, modelling is often done at a coarser grid spacing than one would ideally use. In the lectures, you have learned to derive first- (forward and backward) and second-order accurate spatial discretizations. With more advanced methods that involve more than two grid points, it is possible to derive numerical schemes that are far more accurate than the schemes you have used thus far.

In this assignment, you will work with the linear advection equation

$$
\dfrac{\partial s}{\partial t} = - u \dfrac{\partial s}{\partial x}.
$$

You will work with a system in which a block is placed in the center of the domain and advected to the right. In order to avoid having to deal with boundary discretizations, everything that is advected out of the domain on the right, re-enters the domain on the left. The duration of the simulation will be chosen such that the block ends exactly at the same location as where it started. This we do with the settings below, we have a channel of 100 m, in which we advect the block around with 1 m s$^{-1}$ during 100 s.

```{R problem_definition}
u = 1.
L = 100.
end_time = 100.
```

In order to plot the block, we first define a set of helper functions for the entire assignment and then generate and plot the block.

```{R ref_functions}
# Generate block in middle of domain.
calc_init_state = function(x)
{
  z = abs(x - L/2)
  1.e4 / (1.e4 + exp(1.4*z))
}

calc_init_state_derivative = function(x)
{
  eps = 0.0001
  (calc_init_state(x + eps) - calc_init_state(x - eps)) / (2.*eps)
}

# # Generate gaussian in middle of domain.
# sigma = 1.5
# 
# calc_init_state = function(x)
# {
#   exp(-(x-L/2)^2 / (2*sigma^2))
# }
# 
# calc_init_state_derivative = function(x)
# {
#   - (x - L/2)/(sigma^2) * exp(-(x-L/2)^2 / (2*sigma^2))
# }

calc_error = function(df, n=1.)
{
  error_vec = abs(df$state - calc_init_state(df$x))^n
  error = (sum(error_vec))^(1./n)
  return(error)
}
```

```{R reference_computation, message=FALSE, warning=FALSE}
# Compute reference line to compare solutions against.
ref = data.frame(x=seq(from=0, to=L, by=0.01))
ref$state = calc_init_state(ref$x)
ref$init_dstatedx = calc_init_state_derivative(ref$x)

init_line = list(color='black', dash='dot', width=1.5)
p = plot_ly()
p = layout(p, yaxis=list(range = c(-0.4, 1.4)))
p = add_trace(p, x=ref$x, y=ref$state, name='ref', mode='lines', line=init_line)
p
```

Now, we will integrate the advection equation using the second-order centered discretization in space, combined with the Crank-Nicolson in time. The time discretization we will not touch in this assignment. Study the code below in detail, as this will be your starting point for implementation of more advanced methods. Note that the code is written as a function, which enables you to call it multiple times with different settings. Also, note that the spatial derivative of the initial state is saved (in `init_dstatedx`), which allows for evaluation of the spatial scheme independently.

```{R cn_2nd}
solve_cn_2nd = function(omega, dx, dt)
{
  # Calculation preparation
  n_time = round(end_time / dt)
  N = L/dx
  x = seq(from=0, by=dx, length.out=N)
  state = calc_init_state(x)
  
  M = matrix(0., nrow=N, ncol=N)
  
  M[1, N] = -1./2.
  M[1, 2] =  1./2.
  
  for (i in 2:(N-1))
  {
    M[i, i-1] = -1./2.
    M[i, i+1] =  1./2.
  }
  
  M[N, N-1] = -1./2.
  M[N, 1  ] =  1./2.
  
  M = M/dx
  
  I = diag(N)
  
  # Define the matrices to avoid unnecessary computations.
  N_rhs = (I - omega     * dt * u * M)
  N_lhs = (I + (1-omega) * dt * u * M)
  N_inv = solve(N_lhs)
  
  # Solve the initial derivative for error checking of M
  init_dstatedx = M %*% state
  
  # Time stepping variable.
  time = 0.
  
  for (i in (1:n_time))
  {
    # Evaluate the righthand side.
    v = N_rhs %*% state
    
    # Compute the new state.
    new_state = N_inv %*% v
    
    # update the time and the state.
    time = time + dt
    state = new_state
  }
  
  return(data.frame(x=x, init_dstatedx=init_dstatedx, state=state))
}

cn_2nd = solve_cn_2nd(omega=0.5, dx=0.5, dt=0.1)
```

Now, we can run the code using `0.5` for omega to have Crank-Nicolson, a grid spacing `dx` of `1.` m and a time step `dt` of `0.5` s.

<div class="student_answer">
```{R run_solvers}
cn_2nd = solve_cn_2nd(omega=0.5, dx=1., dt=0.5)
```
</div>

The code below compares the outcome against the initial profile (note that nothing should have changed after a full round of advection).

<div class="student_answer">
```{R error}
print(calc_error(cn_2nd))
```
</div>

The plots below compare the spatial derivative against the exact solution and show the final outcome of the simulation.

<div class="student_answer">
```{R message=FALSE, warning=FALSE}
init_line = list(color='black', dash='dot', width=1.5)
p = plot_ly()
p = add_trace(p, x=cn_2nd$x, y=cn_2nd$init_dstatedx, name='cn_2nd', mode='lines')
p = add_trace(p, x=ref$x, y=ref$init_dstatedx, name='ref', mode='lines', line=init_line)
p
```
</div>

<div class="student_answer">
```{R message=FALSE, warning=FALSE}
init_line = list(color='black', dash='dot', width=1.5)
p = plot_ly()
p = layout(p, yaxis=list(range = c(-0.4, 1.4)))
p = add_trace(p, x=cn_2nd$x, y=cn_2nd$state, name='cn_2nd', mode='lines')
p = add_trace(p, x=ref$x, y=ref$state, name='ref', mode='lines', line=init_line)
p
```
</div>

Clearly, the final solution does not look good, and this is where the assignment starts.

## Assignment
### The second-order scheme.
1. Improve the accuracy of the second-order `cn_2nd` implementation by decreasing `dt` and `dx` until you find the solution good enough. Think of an objective criterion for *good enough* that allows you to compare solutions.

### The fourth-order scheme. 
As a first step, we will move to a fourth-order spatial discretization `cn_4th`. In order to do so, we need four Taylor series for $s(x - 2\Delta x)$, $s(x - \Delta x)$, $s(x + \Delta x)$, and $s(x + 2 \Delta x)$.

2. Work out the four Taylor series until the fifth derivative.

In order to find a derivation, we would like to have a function

$$\dfrac{\partial s}{\partial x} = a\,s(x - 2\Delta x) + b\,s(x - \Delta x) + c\,s(x + \Delta x) + d\,s(x + 2 \Delta x).
$$

3. Formulate a matrix-vector equation in the form 
$$
\begin{bmatrix}
. & . & . & . \\
. & . & . & . \\
. & . & . & . \\
. & . & . & .
\end{bmatrix}
\cdot
\begin{bmatrix}
a \\
b \\
c \\
d
\end{bmatrix}
=
\begin{bmatrix}
. \\
. \\
. \\
.
\end{bmatrix}
$$
Think carefully about the vector on the RHS. You need to find the first derivative, and at the same time you need to ensure that the next three error terms add up to zero in order to end up with fourth-order accuracy. 

4. Solving the system by hand in order to find coefficients $(a,b,c,d)$ for the discretization. TIP: simplify the coefficients of the matrix and vector as much as you can before starting the elimination.

5. Copy the code from the `cn_2nd` solver and build a solver for the `cn_4th` scheme. Add the solution to the plots and error computation and compare the results.

6. Test how much you can increase the grid spacing `dx` and time step `dt` without losing too much accuracy.

### The fourth-order compact scheme.
The usage of four neighboring points delivers fourth-order accuracy, but also introduces inprecise approximation of fine-scale structures due to the wide stencil. Padé, a mathematician who lived in the beginning of 20th century, invented an alternative method (read theory in https://doi.org/10.1016/0021-9991(92)90324-R). Rather than using the Taylor series evaluated at four neighboring points, he used only the left and right neighboring points, but also introduced a Taylor series for the derivative at those points.
$$
\dfrac{\partial s}{\partial x}(x + \Delta x) = \dfrac{\partial s}{\partial x}(x) + \dfrac{\Delta x}{1!} \dfrac{\partial^2 s}{\partial x^2}(x) + \dots
$$
Schemes that combine Taylor series of neighboring points and their derivatives are called *compact schemes*, because of the small width of the stencil compared to conventional schemes such as `cn_2nd` and `cn_4th`.

In order to derive the fourth-order compact spatial discretization `cn_compact_4th`, we need four Taylor series: $s(x - \Delta x)$, $s(x + \Delta x)$, $\dfrac{\partial s}{\partial x}(x - \Delta x)$, and $\dfrac{\partial s}{\partial x}(x + \Delta x)$.

7. Work out the four Taylor series until the fifth derivative.

8. Again, build a linear system in the same way as for the `cn_4th` scheme and solve again coefficients $(a, b, c, d)$.

9. The solution of a compact scheme is implicit in space, because the computed $\partial s / \partial x (x)$ is a function of its neighboring derivatives. Therefore, we have to write the numerical solution for the derivative as:
$$
M_{dsdx}
\cdot
\begin{bmatrix}
\left. \dfrac{\partial s}{\partial x} \right|_1 \\
\vdots \\
\left. \dfrac{\partial s}{\partial x} \right|_n \\
\end{bmatrix}
=
M_s
\cdot
\begin{bmatrix}
s_1 \\
\vdots \\
s_n \\
\end{bmatrix},
$$
with the matrix $M$ that is needed to compute the derivative from the state then acquired as $M_{dsdx}^{-1} \cdot M_s$. Keep in mind that you do not have to solve this by hand, R can do the inversion for you.

10. Implement the `cn_compact_4th` scheme, and compare the required `dx` and `dt` to the previous computations and test how much `dx` and `dt` can be increased without losing accuracy.

### BONUS: Using Fast-Fourier Transforms (only if time permits)
There is an even more accurate method that is only possible for periodic domains (what goes out on one side comes back into the other) with uniform grid spacing `dx`. This is the case for our problem, but also for a global weather or climate model. This method makes use of discrete Fourier transforms, using an algorithm called the Fast-Fourier Transform (FFT) (https://en.wikipedia.org/wiki/Discrete_Fourier_transform).

The rationale behind the Fourier transform is that we can write any continuous function as a sum of waves (called a Fourier mode) with different wave numbers. In a discrete Fourier transform, we transform a state of `n` points into a set of `n` waves with wavenumbers (written in the order as the R `fft` function returns them)
$$
k = \dfrac{2 \pi}{L} \cdot \left( 0, 1, \dots, \dfrac{N}{2}-1, -\dfrac{N}{2}, - \dfrac{N}{2}+1, \dots, -1 \right).
$$
Note the sign change after the middle point.

The FFT of our discretized state $s$ can for each wave number be written as
$$
\hat{s}_n = \dfrac{1}{N} \sum_{m = 1}^{N} s_m e^{i k_n x_m},
$$
with each $n$ representing one value of the wave number vector $k$ written above. Note that $\hat{s}_n$ is a complex number with a real and imaginary part that together determine the amplitude and phase of the wave. The entire vector $\hat{s}$ can be acquired at once from state $s$ by execution of the command `fft(s)`.

For each Fourier mode, it is possible to compute the derivative exactly:
$$
\dfrac{\partial \hat{s}_n}{\partial x} = ik_n\hat{s}_n
$$
In R, one can write the imaginary number $i$ as `1i`. This shows the power of the FFT method: spatial derivatives can be computed without any errors involved.

The inverse FFT can be computed to transform the computed derivative back to real space using `fft(s, inverse=TRUE)`. After back transformation, you need to divide out the number of grid points and take the real part of the solution. This has to do with the implementation of the FFT algorithm in R.

All in all, the procedure looks as following:

```{R eval=FALSE}
# Compute the FFT of the state s.
s_fft = fft(s)

# Code to compute derivative.
# dsdx_fft =

# Transform the derivative back to real space.
dsdx = fft(dsdx_fft, inverse=TRUE)
# Divide out the length of the vector.
dsdx = dsdx / length(s)
# Take the real part.
dsdx = Re(dsdx)
```

11. Implement the FFT-based solver, and compare the required `dx` and `dt` to the previous computations. Check how much both can be increased without losing accuracy.

12. Check whether the FFT method is truly free of spatial errors.

**END OF ASSIGNMENT**

<div class="answer">
```{R cn_4th}
solve_cn_4th = function(omega, dx, dt)
{
  # Calculation preparation
  n_time = round(end_time / dt)
  N = L/dx
  x = seq(from=0, by=dx, length.out=N)
  state = calc_init_state(x)
  
  M = matrix(0., nrow=N, ncol=N)
  
  M[1, N-1] =  1./12.
  M[1, N  ] = -2./ 3.
  M[1, 2  ] =  2./ 3.
  M[1, 3  ] = -1./12.
  
  M[2, N] =  1./12.
  M[2, 1] = -2./ 3.
  M[2, 3] =  2./ 3.
  M[2, 4] = -1./12.
  
  for (i in 3:(N-2))
  {
    M[i, i-2] =  1./12.
    M[i, i-1] = -2./ 3.
    M[i, i+1] =  2./ 3.
    M[i, i+2] = -1./12.
  }
  
  M[N-1, N-3] =  1./12.
  M[N-1, N-2] = -2./ 3.
  M[N-1, N  ] =  2./ 3.
  M[N-1, 1  ] = -1./12.
  
  M[N, N-2] =  1./12.
  M[N, N-1] = -2./ 3.
  M[N, 1  ] =  2./ 3.
  M[N, 2  ] = -1./12.
  
  M = M / dx
  
  I = diag(N)
  
  # Define the matrices to avoid unnecessary computations.
  N_rhs = (I - omega     * dt * u * M)
  N_lhs = (I + (1-omega) * dt * u * M)
  N_inv = solve(N_lhs)
  
  # Solve the initial derivative for error checking of M
  init_dstatedx = M %*% state
  
  # Time stepping variable.
  time = 0.
  
  for (i in (1:n_time))
  {
    # Evaluate the righthand side.
    v = N_rhs %*% state
    
    # Compute the new state.
    new_state = N_inv %*% v
    
    # update the time and the state.
    time = time + dt
    state = new_state
  }
  
  return(data.frame(x=x, init_dstatedx=init_dstatedx, state=state))
}
```
</div>

<div class="answer">
```{R cn_compact_4th}
solve_cn_compact_4th = function(omega, dx, dt)
{
  # Calculation preparation
  n_time = round(end_time / dt)
  N = L/dx
  x = seq(from=0, by=dx, length.out=N)
  state = calc_init_state(x)
  
  M_a = matrix(0., nrow=N, ncol=N)
  M_alpha = matrix(0., nrow=N, ncol=N)
  
  M_a[1, N] = -3./4.
  M_a[1, 2] =  3./4.
  
  for (i in 2:(N-1))
  {
    M_a[i, i-1] = -3./4.
    M_a[i, i+1] =  3./4.
  }
  
  M_a[N, N-1] = -3./4.
  M_a[N, 1  ] =  3./4.
  
  M_alpha[1, N] = 1./4.
  M_alpha[1, 1] = 1.
  M_alpha[1, 2] = 1./4.
  
  for (i in 2:(N-1))
  {
    M_alpha[i, i-1] = 1./4.
    M_alpha[i, i  ] = 1.
    M_alpha[i, i+1] = 1./4.
  }
  
  M_alpha[N, N-1] = 1./4.
  M_alpha[N, N  ] = 1.
  M_alpha[N, 1  ] = 1./4.
  
  M = solve(M_alpha) %*% (M_a/dx)
  
  I = diag(N)
  
  # Define the matrices to avoid unnecessary computations.
  N_rhs = (I - omega     * dt * u * M)
  N_lhs = (I + (1-omega) * dt * u * M)
  N_inv = solve(N_lhs)
  
  # Solve the initial derivative for error checking of M
  init_dstatedx = M %*% state
  
  # Time stepping variable.
  time = 0.
  
  for (i in (1:n_time))
  {
    # Evaluate the righthand side.
    v = N_rhs %*% state
    
    # Compute the new state.
    new_state = N_inv %*% v
    
    # update the time and the state.
    time = time + dt
    state = new_state
  }
  
  return(data.frame(x=x, init_dstatedx=init_dstatedx, state=state))
}
```
</div>

<div class="answer">
```{R cn_compact_6th}
solve_cn_compact_6th = function(omega, dx, dt)
{
  # Calculation preparation
  n_time = round(end_time / dt)
  N = L/dx
  x = seq(from=0, by=dx, length.out=N)
  state = calc_init_state(x)
  
  M_a = matrix(0., nrow=N, ncol=N)
  M_alpha = matrix(0., nrow=N, ncol=N)
  
  M_a[1, N-1] =  -1./36.
  M_a[1, N  ] = -14./18.
  M_a[1, 2  ] =  14./18
  M_a[1, 3  ] =   1./36.
  
  M_a[2, N] =  -1./36.
  M_a[2, 1] = -14./18
  M_a[2, 3] =  14./18
  M_a[2, 4] =   1./36.
  
  for (i in 3:(N-2))
  {
    M_a[i, i-2] =  -1./36.
    M_a[i, i-1] = -14./18
    M_a[i, i+1] =  14./18
    M_a[i, i+2] =   1./36.
  }
  
  M_a[N-1, N-3] =  -1./36.
  M_a[N-1, N-2] = -14./18
  M_a[N-1, N  ] =  14./18
  M_a[N-1, 1  ] =   1./36.
  
  M_a[N, N-2] =  -1./36.
  M_a[N, N-1] = -14./18
  M_a[N, 1  ] =  14./18
  M_a[N, 2  ] =   1./36.
  
  M_alpha[1, N] = 1./3.
  M_alpha[1, 1] = 1.
  M_alpha[1, 2] = 1./3.
  
  for (i in 2:(N-1))
  {
    M_alpha[i, i-1] = 1./3.
    M_alpha[i, i  ] = 1.
    M_alpha[i, i+1] = 1./3.
  }
  
  M_alpha[N, N-1] = 1./3.
  M_alpha[N, N  ] = 1.
  M_alpha[N, 1  ] = 1./3.
  
  M = solve(M_alpha) %*% (M_a/dx)
  
  I = diag(N)
  
  # Define the matrices to avoid unnecessary computations.
  N_rhs = (I - omega     * dt * u * M)
  N_lhs = (I + (1-omega) * dt * u * M)
  N_inv = solve(N_lhs)
  
  # Solve the initial derivative for error checking of M
  init_dstatedx = M %*% state

  # Time stepping variable.
  time = 0.
  
  for (i in (1:n_time))
  {
    # Evaluate the righthand side.
    v = N_rhs %*% state
    
    # Compute the new state.
    new_state = N_inv %*% v
    
    # update the time and the state.
    time = time + dt
    state = new_state
  }
  
  return(data.frame(x=x, init_dstatedx=init_dstatedx, state=state))
}
```
</div>

<div class="answer">
```{R cn_fft}
solve_cn_fft = function(omega, dx, dt)
{
  # Calculation preparation
  n_time = round(end_time / dt)
  N = L/dx
  x = seq(from=0, by=dx, length.out=N)
  state = calc_init_state(x)
  
  k = seq(from=0, to=N-1)
  k[(N/2+1):N] = k[(N/2+1):N] - length(k)
  k = 2.*pi*k/L
  fac_rhs = omega*dt*u*1i*k
  fac_lhs = (1.-omega)*dt*u*1i*k
  
  # Solve the initial derivative for error checking of fft procedure
  init_dstatedx = Re(fft(1i*k*fft(state), inverse=TRUE)) / length(state)
  
  # Time stepping variable.
  time = 0.

  # Fourier transform the state and solve model in spectral space.
  state_fft = fft(state)
  
  for (i in (1:n_time))
  {
    # Compute the new state.
    new_state_fft = (1. - fac_rhs) / (1. + fac_lhs) * state_fft
    
    # Update the time and the state.
    time = time + dt
    state_fft = new_state_fft
  }
  
  # Inverse Fourier transform the state.
  state = Re(fft(state_fft, inverse=TRUE)) / length(state)
  
  return(data.frame(x=x, init_dstatedx=init_dstatedx, state=state))
}
```
</div>

<div class="answer">
```{R run_solvers_answer}
cn_2nd         = solve_cn_2nd         (omega=0.5, dx=1., dt=0.5)
cn_4th         = solve_cn_4th         (omega=0.5, dx=1., dt=0.5)
cn_compact_4th = solve_cn_compact_4th (omega=0.5, dx=1., dt=0.5)
cn_compact_6th = solve_cn_compact_6th (omega=0.5, dx=1., dt=0.5)
cn_fft         = solve_cn_fft         (omega=0.5, dx=1., dt=0.5)
```
</div>

<div class="answer">
```{R error_answer}
print(calc_error(cn_2nd, 2.))
print(calc_error(cn_4th, 2.))
print(calc_error(cn_compact_4th, 2.))
print(calc_error(cn_compact_6th, 2.))
print(calc_error(cn_fft, 2.))
```
</div>

<div class="answer">
```{R message=FALSE, warning=FALSE}
init_line = list(color='black', dash='dot', width=1.5)
p = plot_ly()
p = add_trace(p, x=cn_2nd$x, y=cn_2nd$init_dstatedx, name='cn_2nd', mode='lines')
p = add_trace(p, x=cn_4th$x, y=cn_4th$init_dstatedx, name='cn_4th', mode='lines')
p = add_trace(p, x=cn_compact_4th$x, y=cn_compact_4th$init_dstatedx, name='cn_compact_4th', mode='lines')
p = add_trace(p, x=cn_compact_6th$x, y=cn_compact_6th$init_dstatedx, name='cn_compact_6th', mode='lines')
p = add_trace(p, x=cn_fft$x, y=cn_fft$init_dstatedx, name='cn_fft', mode='lines')
p = add_trace(p, x=ref$x, y=ref$init_dstatedx, name='ref', mode='lines', line=init_line)
p
```
</div>

<div class="answer">
```{R message=FALSE, warning=FALSE}
init_line = list(color='black', dash='dot', width=1.5)
p = plot_ly()
p = layout(p, yaxis=list(range = c(-0.4, 1.4)))
p = add_trace(p, x=cn_2nd$x, y=cn_2nd$state, name='cn_2nd', mode='lines')
p = add_trace(p, x=cn_4th$x, y=cn_4th$state, name='cn_4th', mode='lines')
p = add_trace(p, x=cn_compact_4th$x, y=cn_compact_4th$state, name='cn_compact_4th', mode='lines')
p = add_trace(p, x=cn_compact_6th$x, y=cn_compact_6th$state, name='cn_compact_6th', mode='lines')
p = add_trace(p, x=cn_fft$x, y=cn_fft$state, name='cn_fft', mode='lines')
p = add_trace(p, x=ref$x, y=ref$state, name='ref', mode='lines', line=init_line)
p
```
</div>
