---
title: "Finite differences 3 extended"
author: "The WANT team"
date: "24/09/2018"
output:
  html_document:
    css: ../../want.css
    toc: yes
    toc_depth: 2
  pdf_document:
    toc: yes
    toc_depth: '2'
---
<!-- include the hint.js -->
<script src="../../hints.js"></script>

## Exercise 1
<div class="exercise">
2.1.1 Discretise the equation using a forward differencing scheme in time and a central scheme in space (both first and second order derivative). Use the omega notation given above to solve for the explicit, implicit and Crank-Nicolson integration scheme. Make sure to use the notation shown in Section 1.1 of the markdown (last equation).
</div>

<div class="answer">
$$
\dfrac{s^{n+1}_i - s^{n}_{i}}{\Delta t} = 
\omega\,\left(-u\dfrac{s^{n}_{i+1}-s^{n}_{i-1}}{2\Delta x} + D\dfrac{s^{n}_{i-1}-2s^{n}_{i}+s^{n}_{i+1}}{\Delta x^2} \right) 
+ (1-\omega)\,\left(-u\dfrac{s^{n+1}_{i+1}-s^{n+1}_{i-1}}{2\Delta x} + D\dfrac{s^{n+1}_{i-1}-2s^{n+1}_{i}+s^{n+1}_{i+1}}{\Delta x^2} \right)
$$  
</div>

This equation can be organised in such a way that it can be inserted in the standard matrix equation, which you will do in the exercise below
$$
Ms^{n+1} = v
$$

<div class="exercise">
2.1.2 Reorganise the equation from exercise 2.1.1 to have all terms about the new time-step `n+1` on the left-hand side and everything else on the right-hand side.
</div>

<div class="answer">
$$
\dfrac{s^{n+1}_i}{\Delta t} 
- \left( 1-\omega)(-u\dfrac{s^{n+1}_{i+1}-s^{n+1}_{i-1}}{2\Delta x} + D\dfrac{s^{n+1}_{i-1}-2s^{n+1}_{i}+s^{n+1}_{i+1}}{\Delta x^2} \right) = \dfrac{s^{n}_{i}}{\Delta t} + \omega\,\left(-u\dfrac{s^{n}_{i+1}-s^{n}_{i-1}}{2\Delta x} + D\dfrac{s^{n}_{i-1}-2s^{n}_{i}+s^{n}_{i+1}}{\Delta x^2} \right)
$$  
</div>

<div class="question">
2.1.3 The equation obtained from the previous exercise can be written in the following way:
$$
as^{n+1}_{i-1} + bs^{n+1}_{i} + cs^{n+1}_{i+1} = d
$$
Find the coefficients `a`, `b`, `c` and `d`.
</div>

<div class="answer">
$$
as^{n+1}_{i-1} = -(1-\omega)(-u\dfrac{-s^{n+1}_{i-1}}{2\Delta x} + D\dfrac{s^{n+1}_{i-1}}{\Delta x^2})\\
a = (\omega-1)(\dfrac{u}{2\Delta x} + \dfrac{D}{\Delta x^2})
$$
$$
bs^{n+1}_{i} = \dfrac{s^{n+1}_{i}}{\Delta t} - (1-\omega)(D\dfrac{-2s^{n+1}_{i}}{\Delta x^2})\\
b = \dfrac{1}{\Delta t} + (\omega-1)(\dfrac{-2D}{\Delta x^2})
$$
$$
cs^{n+1}_{i+1} = -(1-\omega)(-u\dfrac{s^{n+1}_{i+1}}{2\Delta x} + D\dfrac{s^{n+1}_{i+1}}{\Delta x^2})\\
c = (\omega-1)(\dfrac{-u}{2\Delta x} + \dfrac{D}{\Delta x^2})
$$
$$
d = \dfrac{s^{n}_{i}}{\Delta t} + \omega\ (-u\dfrac{s^{n}_{i+1}-s^{n}_{i-1}}{2\Delta x} + D\dfrac{s^{n}_{i-1}-2s^{n}_{i}+s^{n}_{i+1}}{\Delta x^2})
$$
</div>

<div class="exercise">
2.1.4 Use the coefficients of the previous equation to set up a the following matrix equation (using two Dirichlet boundaries): 
$$
Ms^{n+1} = v
$$
</div>

<div class="answer">
$$
\begin{bmatrix}
1&.&.&.&.\\
a&b&c&.&.\\
.&a&b&c&.\\
.&.&a&b&c\\
.&.&.&.&1
\end{bmatrix} * 
\begin{bmatrix}
s^{n+1}_{1}\\
s^{n+1}_{2}\\
s^{n+1}_{3}\\
s^{n+1}_{4}\\
s^{n+1}_{5}
\end{bmatrix} = 
\begin{bmatrix}
b_l\\
d_2\\
d_3\\
d_4\\
b_r
\end{bmatrix}
$$
</div>

<div class="question">
2.1.5 Are the matrix and the vector space or time dependent?
</div>

<div class="answer">
Matrix is completely independent, because $\Delta x$ and $\Delta t$ are constant and uniform in space and time. Vector is dependent on both space and time.
</div>

## Exercise 2
<div class="question">
Construct the time stepping `while` loop (similar to the chunks in the **time**-tutorial) and plot the results.
</div>

<div class="comment"> Here ffmpeg might be a great idea but I don't know how to implement that </div>

<div class="answer">
```{R}
# Input variables
domain  = c(0,100)
endtime = 20
dx      = 1
dt      = 1
u       = 1
D       = 1
bl      = 0
br      = 0
omega   = 0

# Function that gives the states for the first time-step
initfun = function(x)
{
    # Gaussian distribution
    exp(-(x-domain[2]/2)^2/2^2)
}

# Calculation preparation
x           = seq(domain[1],domain[2],by=dx)
N           = length(x)
init.state  = initfun(x)

# MATRIX CONSTRUCTION
M = matrix(0,nrow=N,ncol=N)

# for now a dirichlet boundary is used for the solution
M[1,1] = 1
M[N,N] = 1
A      = (omega-1) * ( u/(2*dx) +   D/dx^2 )
B      = (omega-1) * (          - 2*D/dx^2 ) + 1/dt
C      = (omega-1) * (-u/(2*dx) +   D/dx^2 )

for(i in 2:(N-1)){
  M[i,i-1] = A
  M[i,i  ] = B
  M[i,i+1] = C
}

Minv = solve(M)

# Time stepping variable
time        = 0
new.state   = init.state
plotlim     = c(-0.2,1.2)

while(time<endtime)
{
    plot(x,new.state,ylim=plotlim,type="l", xlab="x", ylab ="state")
    prev.state = new.state
    
    V    = c()
    V[1] = bl
    
    for(i in 2:(N-1))
    {
        V[i] = prev.state[i]/dt 
             + omega*(-u*(prev.state[i+1]-prev.state[i-1])/(2*dx) 
             + D*(prev.state[i+1]-2*prev.state[i]+prev.state[i-1])/dx^2)
    }
    
    V[N] = br
    new.state = Minv %*% V
    
    time = time + dt
}
```
</div>

